@startuml
'https://plantuml.com/sequence-diagram

actor User
participant EscenarioJugarView
participant EscenarioJugarController
participant AnimationTimer
participant Partida
participant Bucles


activate EscenarioJugarController
activate EscenarioJugarView

User->EscenarioJugarView: Empezar Partida

EscenarioJugarView->EscenarioJugarController:start()
EscenarioJugarController->EscenarioJugarController: validarInicioPartida()
EscenarioJugarController->EscenarioJugarController: desabilitarSliders()


EscenarioJugarController->AnimationTimer: start()
activate AnimationTimer


User->EscenarioJugarView: Pausar Partida
EscenarioJugarView->EscenarioJugarController: pause()
EscenarioJugarController->AnimationTimer:stop()
User->EscenarioJugarView: Terminar Partida
EscenarioJugarView->EscenarioJugarController:endGame()
EscenarioJugarController->AnimationTimer: stop()
deactivate AnimationTimer
EscenarioJugarController->EscenarioJugarView: cargarArbol()
EscenarioJugarView->User: Arbol Genealogico




newpage Botones Superiores

Participant Gson
Participant EscenariosController


User->EscenarioJugarView: Guardar Partida
EscenarioJugarView->EscenarioJugarController:guardar()
EscenarioJugarController->Gson: toJson()
activate Gson
Gson->Partida: toJson()
deactivate Gson
EscenarioJugarController->AnimationTimer:stop()
deactivate AnimationTimer

User->EscenarioJugarView: Cargar Partida
EscenarioJugarView->EscenarioJugarController:cargar()
EscenarioJugarController->Gson
Gson->Partida: fromJson()
Partida->EscenarioJugarController: return Partida

User->EscenarioJugarView:Menú Principal
EscenarioJugarView->EscenarioJugarController:salir()
EscenarioJugarController->EscenariosController: cargarEscenarioInicio()
deactivate EscenarioJugarController
deactivate EscenarioJugarView
EscenariosController->User: EscenarioInicioView

@enduml