@startuml
'https://plantuml.com/sequence-diagram

actor User
participant EscenarioInicioView
participant EscenarioInicioController
participant EscenarioJugarController
participant EscenariosController

activate EscenariosController
activate EscenarioInicioView
activate EscenarioInicioController
User -> EscenarioInicioView: Nueva Partida
EscenarioInicioView->EscenarioInicioController: nuevapartida()
EscenarioInicioController->EscenariosController: cargarEscenarioJugar()
deactivate EscenarioInicioController
deactivate EscenarioInicioView
EscenariosController->EscenarioJugarController: nuevo controlador
EscenariosController->User: EscenarioJugarView

activate EscenarioInicioView
activate EscenarioInicioController
User -> EscenarioInicioView: Cargar Partida
EscenarioInicioView->EscenarioInicioController: cargarpartida()
EscenarioInicioController->EscenariosController: cargarEscenarioJugarCargar()
deactivate EscenarioInicioController
deactivate EscenarioInicioView
EscenariosController->EscenarioJugarController: nuevo controlador, setCargar()
EscenarioJugarController->EscenarioJugarController: cargar()
EscenariosController->User: EscenarioJugarView

@enduml