@startuml
'https://plantuml.com/sequence-diagram

actor User
participant EscenarioInicio
participant EscenarioJugarController
participant EscenarioCargarController

activate EscenarioInicio
User -> EscenarioInicio: Nueva Partida


EscenarioInicio -> EscenarioJugarController: nuevaPartida()
activate EscenarioJugarController
EscenarioJugarController -> User: EscenarioJugarView
deactivate EscenarioInicio
deactivate EscenarioJugarController

User -> EscenarioInicio: Cargar Partida
activate EscenarioInicio
EscenarioInicio -> EscenarioCargarController: cargarPartida()
activate EscenarioCargarController
EscenarioCargarController -> User: EscenarioCargarView
deactivate EscenarioCargarController

deactivate EscenarioInicio
deactivate EscenarioCargarController
@enduml