@startuml
'https://plantuml.com/sequence-diagram

actor User
participant EscenarioJugarView
participant EscenarioJugarController
participant Casilla
participant Partida

activate EscenarioJugarView
User->EscenarioJugarView: Modificar Tablero

activate EscenarioJugarController
EscenarioJugarView->EscenarioJugarController: aceptarTablero()/restablecerTablero()
EscenarioJugarController->EscenarioJugarController: eliminarTablero()
EscenarioJugarController->EscenarioJugarController: crearTablero()

activate Casilla
EscenarioJugarController->Casilla: new Casilla()
Casilla->EscenarioJugarController: Casilla
EscenarioJugarController->Partida: getListaCasillas().addCasilla()
EscenarioJugarController->EscenarioJugarView: dibuja el tablero
EscenarioJugarView->User:Tablero


newpage Aceptar Individuos/Entorno
User->EscenarioJugarView: Modificar Individuos
EscenarioJugarView->EscenarioJugarController:aceptarTablero()/restablecerTablero()
EscenarioJugarController->Partida: crearPartida()
activate Partida
Partida->EscenarioJugarController: return Partida
User->EscenarioJugarView: Modificar Recursos
EscenarioJugarView->EscenarioJugarController:aceptarTablero()/restablecerTablero()
EscenarioJugarController->Partida: crearPartida()
Partida->EscenarioJugarController: return Partida


deactivate Partida
deactivate Casilla

newpage Aceptar General

participant Bucles

User->EscenarioJugarView: Aceptar
EscenarioJugarView->EscenarioJugarController:aceptarTablero()

EscenarioJugarController->EscenarioJugarController:eliminarTablero()

EscenarioJugarController->Partida:crearPartida()
Partida->EscenarioJugarController:return Partida

EscenarioJugarController->Bucles: new Bucles()
Bucles->EscenarioJugarController:return Bucles

EscenarioJugarController->EscenarioJugarController:crearTablero
activate EscenarioJugarController #FFBBBB
EscenarioJugarController->Partida:getColumnas(), getFilas()
Partida->EscenarioJugarController:return Columnas, Filas
EscenarioJugarController->Casilla: new Casilla(i,j)
Casilla->EscenarioJugarController:return Casilla
EscenarioJugarController->Casilla:addEventFilter()
EscenarioJugarController->Partida:getListaCasillas.addCasilla()
EscenarioJugarController->EscenarioJugarView:return Tablero
deactivate EscenarioJugarController
EscenarioJugarView->User: Tablero
EscenarioJugarController->EscenarioJugarController:cambiarVelocidad()
deactivate EscenarioJugarController
deactivate EscenarioJugarView
@enduml